blank_issues_enabled: false
contact_links:
  - name: 游닄 Dokument치ci칩
    url: https://github.com/erbnrabbit1987/nincsenekfenyek/tree/main/docs
    about: Tekintsd meg a projekt dokument치ci칩j치t
  - name: 游빍 Tesztesetek
    url: https://github.com/erbnrabbit1987/nincsenekfenyek/issues?q=is%3Aissue+label%3Atest-case
    about: Tekintsd meg a teszteseteket
  - name: 游늶 Use Cases
    url: https://github.com/erbnrabbit1987/nincsenekfenyek/blob/main/USE_CASES.md
    about: Tekintsd meg a use case dokument치ci칩t




